.github/workflows/ci-cd.yml
src/main/java/com/beautymeongdang/domain/quote/entity/Quote.java

Refactor : Quote Entity 수정

---

src/main/java/com/beautymeongdang/BeautymeongdangApplication.java
src/main/java/com/beautymeongdang/domain/shop/entity/Shop.java
src/main/java/com/beautymeongdang/domain/user/entity/Customer.java

Refactor : @EnableJpaAuditing 추가 및 BigDecimal 수정

Refactor : @EnableJpaAuditing 추가 및 BigDecimal 수정

---

src/main/java/com/beautymeongdang/global/config/CodeInitializer.java

Refactor : 공통코드 수정

---

src/main/java/com/beautymeongdang/domain/dog/entity/Dog.java
src/main/java/com/beautymeongdang/domain/quote/controller/QuoteRequestController.java
src/main/java/com/beautymeongdang/domain/quote/dto/GroomerDirectRequestListResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/quote/service/QuoteRequestService.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Feat : 미용사 1:1 견적서 요청 조회 구현

---

src/main/java/com/beautymeongdang/domain/quote/dto/CreateInsertRequestGroomerRequestDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/CreateInsertRequestGroomerResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/repository/DirectQuoteRequestRepository.java

Feat/#23/request quote/groomer

---

src/main/java/com/beautymeongdang/domain/quote/controller/QuoteRequestController.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerSendQuoteRequestResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/quote/service/QuoteRequestService.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Feat : 미용사가 견적서 보낸 견적 요청 조회 구현

Feat : 미용사가 견적서 보낸 견적 요청 조회 구현

---

src/main/java/com/beautymeongdang/domain/quote/controller/QuoteRequestController.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Fix : 괄호 수정

---

src/main/java/com/beautymeongdang/domain/quote/controller/QuoteRequestController.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerRequestDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/service/QuoteRequestService.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Feat : 미용사가 견적서 요청 상세 조회 구현

---

src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerRequestDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Refactor : responseDto dogId 삭제

Refactor : responseDto dogId 삭제

---

src/main/java/com/beautymeongdang/domain/quote/controller/QuoteRequestController.java
src/main/java/com/beautymeongdang/domain/quote/dto/UpdateGroomerRequestRejectionRequestDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/UpdateGroomerRequestRejectionResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/entity/DirectQuoteRequestId.java
src/main/java/com/beautymeongdang/domain/quote/service/QuoteRequestService.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Feat : 미용사 1:1 맞춤 견적 요청 거절 구현

---

src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerRequestDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Refactor : responseDto dogId 추가

Refactor : responseDto dogId 추가

---

src/main/java/com/beautymeongdang/domain/quote/controller/QuoteController.java
src/main/java/com/beautymeongdang/domain/quote/dto/CreateGroomerQuoteRequestDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/CreateGroomerQuoteResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/service/QuoteService.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteServiceImpl.java

Feat : 미용사 견적서 작성 구현

---

src/main/java/com/beautymeongdang/domain/quote/controller/QuoteController.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerQuoteDetailRequestDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerQuoteDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRepository.java
src/main/java/com/beautymeongdang/domain/quote/service/QuoteService.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteServiceImpl.java

Feat : 미용사가 보낸 견적서 상세 조회 (미용사)

Feat : 미용사가 보낸 견적서 상세 조회 (미용사)

---

src/main/java/com/beautymeongdang/domain/quote/entity/Quote.java
src/main/java/com/beautymeongdang/domain/quote/entity/QuoteRequest.java
src/main/java/com/beautymeongdang/global/oauth2/KakaoResponse.java

Deploy: login deploy last 수정

---

src/main/java/com/beautymeongdang/domain/quote/controller/QuoteRequestController.java
src/main/java/com/beautymeongdang/domain/quote/service/QuoteRequestService.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java

Refactor : request sigunguId -> groomerId 수정

Refactor : request sigunguId -> groomerId 수정

---

src/main/java/com/beautymeongdang/domain/review/controller/ReviewController.java
src/main/java/com/beautymeongdang/domain/review/dto/CreateReviewRequestDto.java
src/main/java/com/beautymeongdang/domain/review/dto/CreateReviewResponseDto.java
src/main/java/com/beautymeongdang/domain/review/service/ReviewService.java
src/main/java/com/beautymeongdang/domain/review/service/impl/ReviewServiceImpl.java

Feat : 리뷰 작성

---

src/main/java/com/beautymeongdang/domain/review/controller/LikeController.java
src/main/java/com/beautymeongdang/domain/review/controller/ReviewController.java
src/main/java/com/beautymeongdang/domain/review/service/LikeService.java
src/main/java/com/beautymeongdang/domain/review/service/ReviewService.java
src/main/java/com/beautymeongdang/domain/review/service/impl/LikeServiceImpl.java
src/main/java/com/beautymeongdang/domain/review/service/impl/ReviewServiceImpl.java

Refactor: 좋아요 기능 controller 이동

---

src/main/java/com/beautymeongdang/domain/review/controller/ReviewController.java
src/main/java/com/beautymeongdang/domain/review/dto/CreateUpdateReviewResponseDto.java
src/main/java/com/beautymeongdang/domain/review/dto/UpdateReviewRequestDto.java
src/main/java/com/beautymeongdang/domain/review/service/ReviewService.java
src/main/java/com/beautymeongdang/domain/review/service/impl/ReviewServiceImpl.java

Feat : 리뷰 수정 구현

---

src/main/java/com/beautymeongdang/domain/review/repository/ReviewsImageRepository.java
src/main/java/com/beautymeongdang/domain/review/service/impl/ReviewServiceImpl.java

Refactor : 리뷰 이미지 삭제 수정

---

src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/quote/repository/SelectedQuoteRepository.java
src/main/java/com/beautymeongdang/domain/user/controller/MainController.java
src/main/java/com/beautymeongdang/domain/user/dto/GetMainGroomerResponseDto.java
src/main/java/com/beautymeongdang/domain/user/dto/GetMainGroomerTotalRequestResponseDto.java
src/main/java/com/beautymeongdang/domain/user/service/MainService.java
src/main/java/com/beautymeongdang/domain/user/service/impl/MainServiceImpl.java

Feat : 미용사 메인 페이지 구현

---

src/main/java/com/beautymeongdang/domain/review/service/impl/ReviewServiceImpl.java

Refactor : 리뷰 작성 이미지 개수 수정

---

src/main/java/com/beautymeongdang/domain/review/controller/ReviewController.java
src/main/java/com/beautymeongdang/domain/review/service/impl/ReviewServiceImpl.java
src/main/java/com/beautymeongdang/domain/user/controller/GroomerController.java
src/main/java/com/beautymeongdang/domain/user/dto/UpdateGroomerPortfolioDto.java
src/main/java/com/beautymeongdang/domain/user/entity/GroomerPortfolioImage.java
src/main/java/com/beautymeongdang/domain/user/repository/GroomerPortfolioImageRepository.java
src/main/java/com/beautymeongdang/domain/user/service/GroomerService.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java

Feat : 미용사 포트폴리오 수정 구현

---

src/main/java/com/beautymeongdang/global/oauth2/OAuth2AuthorizationClient.java

OAuth2AuthorizationClient

---

src/main/java/com/beautymeongdang/global/config/SecurityConfig.java

SecurityConfig 수정

---

src/main/java/com/beautymeongdang/global/jwt/JwtProvider.java
src/main/resources/application-dev.properties

accessTokenCookie.setSecure(false); 테스트

accessTokenCookie.setSecure(false); 테스트

---

src/main/java/com/beautymeongdang/global/jwt/JwtProvider.java
src/main/java/com/beautymeongdang/global/login/controller/OAuth2Controller.java
src/main/resources/application-dev.properties

redirect 테스트

---

src/main/java/com/beautymeongdang/global/login/controller/OAuth2Controller.java
src/main/resources/application-dev.properties

application-dev.properties 수정

---

src/main/java/com/beautymeongdang/domain/quote/repository/SelectedQuoteRepository.java
src/main/java/com/beautymeongdang/domain/user/controller/MypageController.java
src/main/java/com/beautymeongdang/domain/user/dto/GetGroomerMypageResponseDto.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/MypageServiceImpl.java
src/main/java/com/beautymeongdang/domain/user/service/MypageService.java

Feat : 미용사 마이페이지 조회 구현

---

src/main/java/com/beautymeongdang/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/beautymeongdang/domain/chat/repository/ChatRepository.java
src/main/java/com/beautymeongdang/domain/payment/repository/PaymentRepository.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRepository.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/quote/repository/SelectedQuoteRepository.java
src/main/java/com/beautymeongdang/domain/review/repository/ReviewRepository.java
src/main/java/com/beautymeongdang/domain/user/controller/GroomerController.java
src/main/java/com/beautymeongdang/domain/user/dto/DeleteGroomerProfileResponseDto.java
src/main/java/com/beautymeongdang/domain/user/dto/GetGroomerMypageResponseDto.java
src/main/java/com/beautymeongdang/domain/user/service/GroomerService.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/MypageServiceImpl.java

Feat : 미용사 프로필 논리적 삭제 구현
Refactor : 미용사 마이페이지 nickname -> username 수정

Feat : 미용사 프로필 논리적 삭제 구현

---

src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteServiceImpl.java
src/main/java/com/beautymeongdang/domain/user/dto/GetMainGroomerTotalRequestResponseDto.java
src/main/java/com/beautymeongdang/global/common/repository/CommonCodeRepository.java

Refactor: 미용사 메인, 견적서 작성 공통코드 수정

---

src/main/resources/application-dev.properties

https://frontend-omega-rust.vercel.app/login/oauth2/code/google

---

src/main/resources/application-dev.properties

https://beautymeongdang.vercel.app/login/oauth2/code/google

---

src/main/java/com/beautymeongdang/global/config/SecurityConfig.java
src/main/resources/application-dev.properties

cors 에러 수정

---

src/main/java/com/beautymeongdang/domain/dog/service/impl/DogServiceImpl.java

Refactor: 반려견 공통코드 수정(db에 코드 ID들어가게)

---

src/main/java/com/beautymeongdang/global/oauth2/OAuth2AuthorizationClient.java

locale 오류 수정

---

src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerQuoteDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerQuoteRequestResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerRequestDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerSendQuoteRequestResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteServiceImpl.java

Refactor : 미용사가 보낸 견적서 상세 조회 공통코드 수정
Refactor : 미용사 견적서 요청 조회 공통코드 수정
Refactor : 미용사 견적서 요청 상세 조회 공통코드 수정
Refactor : 미용사 1:1 맞춤 견적서 요청 거절 공통코드 수정

Refactor: 공통코드 수정

---

src/main/java/com/beautymeongdang/domain/quote/entity/Quote.java

Refactor : Quote 엔티티 requestId 수정

Refactor : Quote 엔티티 requestId 수정

---

src/main/java/com/beautymeongdang/domain/user/controller/UserController.java
src/main/java/com/beautymeongdang/domain/user/dto/CustomerRegisterRequestDTO.java
src/main/java/com/beautymeongdang/domain/user/dto/GroomerRegisterRequestDTO.java
src/main/java/com/beautymeongdang/domain/user/entity/User.java
src/main/java/com/beautymeongdang/domain/user/service/UserService.java
src/main/java/com/beautymeongdang/domain/user/service/impl/UserServiceImpl.java

고객:
{
"status": 201,
"message": "고객 회원가입 성공",
"data": {
"customerId": 1,
"email": "user@example.com",
"nickname": "사용자닉네임",
"isRegister": true,
"sigunguId": 1,
"sigunguName": "강남구",
"sidoName": "서울특별시"
}
}
미용사:
{
"status": 201,
"message": "미용사 회원가입 성공",
"data": {
"groomerId": 1,
"email": "user@example.com",
"nickname": "사용자닉네임",
"isRegister": true
}
}

회원 추가 정보 기입 

---

src/main/java/com/beautymeongdang/domain/quote/entity/SelectedQuote.java
src/main/java/com/beautymeongdang/global/config/MultipartJackson2HttpMessageConverter.java

MultipartJackson2HttpMessageConverter 생성해서 swagger 멀티파트 오류 fix
(모르고 리뷰없이 머지 해버려서 걍 공백 만들어서 다시 올렸습니다)

Fix :s3 멀티파트 swagger 오류 수정

---

src/main/java/com/beautymeongdang/domain/user/controller/GroomerController.java
src/main/java/com/beautymeongdang/domain/user/dto/UpdateGroomerProfileDto.java
src/main/java/com/beautymeongdang/domain/user/service/GroomerService.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java

Feat : 미용사 프로필 수정 구현

---

src/main/java/com/beautymeongdang/domain/user/controller/GroomerController.java

Refactor : 미용사 프로필 수정 consumes = MediaType.MULTIPART_FORM_DATA_VALUE 추가

Refactor : 미용사 프로필 수정 consumes = MediaType.MULTIPART_FORM_DATA_VALUE 추가

---

src/main/java/com/beautymeongdang/domain/chat/controller/ChatController.java
src/main/java/com/beautymeongdang/domain/chat/dto/GetCustomerChatListResponseDto.java
src/main/java/com/beautymeongdang/domain/chat/dto/GetCustomerKeywordChatListRequestDto.java
src/main/java/com/beautymeongdang/domain/chat/dto/GetGroomerChatListResponseDto.java
src/main/java/com/beautymeongdang/domain/chat/dto/GetGroomerKeywordChatListRequestDto.java
src/main/java/com/beautymeongdang/domain/chat/repository/ChatRepository.java
src/main/java/com/beautymeongdang/domain/chat/service/ChatService.java
src/main/java/com/beautymeongdang/domain/chat/service/impl/ChatServiceImpl.java

Feat : 고객 채팅방 목록 조회 구현
Feat : 고객 채팅방 목록 검색 조회 구현
Feat : 미용사 채팅방 목록 조회 구현
Feat : 미용사 채팅방 목록 검색 조회 구현

Feat: 채팅방 목록 조회 구현

---

src/main/java/com/beautymeongdang/domain/quote/dto/GetGroomerSendQuoteRequestResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/user/entity/Customer.java

Refactor : 견적서 보낸 견적 요청 조회 status 추가 및 공통코드 수정

Refactor : 견적서 보낸 견적 요청 조회 status 추가 및 공통코드 수정

---

src/main/java/com/beautymeongdang/domain/dog/controller/DogController.java
src/main/java/com/beautymeongdang/domain/dog/dto/GetBreedResponseDto.java
src/main/java/com/beautymeongdang/domain/dog/service/DogService.java
src/main/java/com/beautymeongdang/domain/dog/service/impl/DogServiceImpl.java
src/main/java/com/beautymeongdang/global/common/repository/CommonCodeRepository.java
src/main/java/com/beautymeongdang/global/common/repository/GroupCodeRepository.java

Feat : 반려견 견종 목록 조회 구현

---

src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteServiceImpl.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java

Refactor : 미용사 프로필 삭제 - 매장 삭제 수정

Refactor : 미용사 프로필 삭제 - 매장 삭제 수정

---

src/main/java/com/beautymeongdang/domain/quote/dto/GetSelectedQuoteDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/repository/SelectedQuoteRepository.java

Refactor : 미용사 프로필 삭제 - 매장 삭제 수정
Refactor : 미용사가 보낸 견적서 상세 조회 - 견적서 조회 수정

Refactor: 미용사 프로필 삭제, 미용사가 보낸 견적서 상세 조회

---

src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteServiceImpl.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java

Refactor : 미용사 프로필 삭제 수정

---

src/main/java/com/beautymeongdang/domain/user/repository/GroomerPortfolioImageRepository.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java

Refactor : 미용사 포트폴리오 수정 s3 이미지 삭제 수정

Refactor : 미용사 포트폴리오 수정 s3 이미지 삭제 수정

---

src/main/java/com/beautymeongdang/domain/chat/controller/ChatMessageController.java
src/main/java/com/beautymeongdang/domain/chat/dto/GetChatMessageListResponseDto.java
src/main/java/com/beautymeongdang/domain/chat/dto/GetChatMessageResponseDto.java
src/main/java/com/beautymeongdang/domain/chat/entity/ChatMessageImage.java
src/main/java/com/beautymeongdang/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/beautymeongdang/domain/chat/repository/ChatRepository.java
src/main/java/com/beautymeongdang/domain/chat/service/ChatMessageService.java
src/main/java/com/beautymeongdang/domain/chat/service/impl/ChatMessageServiceImpl.java
src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java

Feat : 채팅 조회 구현

---

src/main/java/com/beautymeongdang/domain/user/service/Impl/GroomerServiceImpl.java

Refactor : 미용사 포트폴리오 수정 s3 이미지 저장 수정

Refactor : 미용사 포트폴리오 수정 s3 이미지 저장 수정

---

src/main/java/com/beautymeongdang/domain/quote/dto/CreateInsertRequestAllRequestDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/CreateInsertRequestGroomerRequestDto.java
src/main/java/com/beautymeongdang/domain/quote/dto/GetQuoteDetailResponseDto.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteRequestServiceImpl.java
src/main/java/com/beautymeongdang/domain/quote/service/impl/QuoteServiceImpl.java
src/main/java/com/beautymeongdang/domain/review/repository/ReviewRepository.java

Refactor: Best 미용후기 기준을 리뷰 추천 수가 많은 순으로 변경함 
이 부분만 보면 될 거 같습니다.

Refactor/#90/main customer Best 미용후기 2개 기준 변경

---

src/main/java/com/beautymeongdang/domain/payment/repository/PaymentRepository.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRepository.java
src/main/java/com/beautymeongdang/domain/quote/repository/QuoteRequestRepository.java
src/main/java/com/beautymeongdang/domain/quote/repository/SelectedQuoteRepository.java
src/main/java/com/beautymeongdang/domain/review/repository/ReviewRepository.java
src/main/java/com/beautymeongdang/domain/shop/repository/FavoriteRepository.java
src/main/java/com/beautymeongdang/domain/shop/repository/ShopRepository.java
src/main/java/com/beautymeongdang/domain/shop/service/impl/ShopServiceImpl.java

아니 이거 왜 자꾸 전에 커밋도 올라가지? 논리적 삭제만 보면 될 거 같네요

Refactor/#180/deleteshop 

---

src/main/java/com/beautymeongdang/domain/chat/controller/ChatMessageController.java
src/main/java/com/beautymeongdang/domain/chat/dto/DeleteChatMessageResponseDto.java
src/main/java/com/beautymeongdang/domain/chat/service/ChatMessageService.java
src/main/java/com/beautymeongdang/domain/chat/service/impl/ChatMessageServiceImpl.java

Feat : 채팅 논리적 삭제 구현

---

src/main/java/com/beautymeongdang/domain/review/repository/ReviewRepository.java
src/main/java/com/beautymeongdang/domain/review/repository/ReviewsImageRepository.java
src/main/java/com/beautymeongdang/global/common/scheduler/review/ReviewScheduledController.java
src/main/java/com/beautymeongdang/global/common/scheduler/review/ReviewScheduledService.java

Feat : 리뷰 물리적 삭제 스케줄러 구현
